dist: trusty
sudo: true
language: cpp
compiler:
  - gcc

before_install:
    - sudo apt-get install -qq libboost1.54-dev

install: true

env:
  - CXX_STANDARD=98
  - CXX_STANDARD=11

script: ./build_and_run.sh

notifications:
  email: false
